window.SEARCH_INDEX = [
  // ── Manual ─────────────────────────────────────────────
  { url:'manual-levels.html',        title:'Create a Level',             category:'Manual',    desc:'How to build a new level — LevelInfo asset, scene setup, tile grid, player, LevelManager wiring, and goal configuration.',    keywords:'level create scene LevelInfo tile grid PathTile Start End LevelManager goals setup' },
  { url:'manual-overview.html',      title:'Overview',                   category:'Manual',    desc:'Project setup, asset structure, Prefabs folder, first-run guide and save/load system.',                             keywords:'setup prefabs scenes level save load execution context first run' },
  { url:'manual-instruction.html',   title:'Create an Instruction',      category:'Manual',    desc:'How to write a custom player instruction from scratch using the Instruction base class.',                           keywords:'instruction create custom scriptable object move attack direction validate execute' },
  { url:'manual-instruction-layout.html', title:'Create an Instruction Layout', category:'Manual', desc:'How to duplicate, configure and wire an InstructionLayout prefab — the draggable widget that represents a player instruction on the sheet.', keywords:'instruction layout prefab Action palette drag drop InstructionLayout InstructionModifierLayout InstructionSequenceLayout InstructionUseLayout widget configure' },
  { url:'manual-enemy.html',         title:'Create an Enemy Instruction', category:'Manual',   desc:'How to write an enemy behaviour script using EnemyInstruction and the task system.',                                keywords:'enemy instruction behaviour AI create GetTask task' },
  { url:'manual-interactable.html',  title:'Create an Interactable',     category:'Manual',    desc:'How to implement IInteractable, IPushable, IPickable or IObstacle on a game object.',                              keywords:'interactable door pushable pickup obstacle IInteractable create guide' },
  { url:'manual-traps.html',         title:'Tile Traps',                  category:'Manual',    desc:'How to place and configure PressurePlate and AppearingSpikes tile traps in a level.',                                     keywords:'trap pressure plate appearing spikes tile setup stages lethal damage OnActivated OnDeactivated' },
  { url:'manual-inventory.html',     title:'Inventory System',            category:'Manual',    desc:'Setting up items, equipment and the PlayerInventory — pickup flow and stat bonuses.',                               keywords:'inventory item equipment stat pickup player setup' },
  { url:'manual-audio.html',         title:'Audio Setup',                 category:'Manual',    desc:'Configuring SoundManager, MusicManager, AudioMixer parameters and the SoundSlider UI component.',                  keywords:'audio sound music mixer SoundManager MusicManager SoundSlider setup volume' },

  // ── Scripting — Instructions ───────────────────────────
  { url:'sc-instruction.html',       title:'Instruction',                 category:'Scripting', desc:'Abstract base class for all player instructions. Override Validate() and Execute() to define behaviour.',          keywords:'Instruction abstract base class validate execute direction OnStart OnEnd' },
  { url:'sc-player-instruction.html',title:'PlayerInstruction',           category:'Scripting', desc:'Runtime pair of an Instruction and a Direction placed on the player sheet.',                                        keywords:'PlayerInstruction direction sheet runtime wrapper' },
  { url:'sc-modifier.html',          title:'InstructionModifier',         category:'Scripting', desc:'Wraps a child PlayerInstruction and overrides its direction at runtime — used for Combo branching.',               keywords:'InstructionModifier modifier direction child wrap combo' },
  { url:'sc-sequence.html',          title:'InstructionSequence',         category:'Scripting', desc:'Ordered list of PlayerInstructions executed sequentially within a single turn.',                                    keywords:'InstructionSequence sequence combo ordered list turn AddInstruction' },
  { url:'sc-enemy-instruction.html', title:'EnemyInstruction',            category:'Scripting', desc:'Base class for enemy behaviours. Scheduled by the runner each turn alongside the player.',                         keywords:'EnemyInstruction enemy behaviour AI turn GetTask task runner' },
  { url:'sc-execution-context.html',    title:'ExecutionContext',            category:'Scripting', desc:'Central runtime object — holds references to player, inventory, map, carryTarget and turn interval.',               keywords:'ExecutionContext runtime player inventory map turn interval carryTarget clone' },
  { url:'sc-execution-subscriber.html', title:'IExecutionSuscriber',         category:'Scripting', desc:'Lightweight notification interface for enemies that react to each instruction step — auto-discovered from the enemy hierarchy, no manual wiring required.',  keywords:'IExecutionSuscriber subscriber execute enemy notification auto-discover GetComponentsInChildren ShootSuscriber' },
  { url:'sc-builtin.html',           title:'Built-in Instructions',       category:'Scripting', desc:'Reference for all built-in instructions: Move, Attack, Block, Wait, Heal and Combo types.',                       keywords:'builtin instructions Move Attack Block Wait Heal Combo PickUp Drop built-in' },
  { url:'sc-custom-instruction.html',title:'Custom Instructions',         category:'Scripting', desc:'API and workflow for writing custom ScriptableObject instructions.',                                                 keywords:'custom instruction scriptable object create API workflow' },
  { url:'sc-tasks.html',             title:'Tasks',                       category:'Scripting', desc:'ITaskReceiver interface and async Task system for scheduling per-turn work.',                                       keywords:'Task ITaskReceiver async turn schedule GetTask Status Running Completed' },

  // ── Scripting — Interactables ──────────────────────────
  { url:'sc-interactable.html',      title:'Interactable Interfaces',     category:'Scripting', desc:'IInteractable, IPushable, IPickable, IObstacle and ExecutionContextElement — the full interactable API.',          keywords:'IInteractable IPushable IPickable IObstacle ExecutionContextElement Initialize interface' },
  { url:'sc-builtin-interactables.html',title:'Built-in Interactables',  category:'Scripting', desc:'Reference for all built-in world objects: doors, crates, levers, pickups and more.',                             keywords:'builtin interactable door crate lever pickup tile built-in' },
  { url:'sc-traps.html',             title:'Traps',                       category:'Scripting', desc:'PressurePlate and AppearingSpikes — automatic turn-based tile traps with damage and events.',                      keywords:'trap PressurePlate AppearingSpikes spikes tile damage health stages appearing' },

  // ── Scripting — Inventory ──────────────────────────────
  { url:'sc-inventory.html',         title:'PlayerInventory',             category:'Scripting', desc:'Singleton inventory — add/remove items, query equipped gear and get stat totals.',                                  keywords:'PlayerInventory inventory singleton item equipment stat Add Remove GetStatValue' },
  { url:'sc-items.html',             title:'Item',                        category:'Scripting', desc:'Base ScriptableObject for collectible items — display name, icon, stackable flag, and ApplyEffects for stat modifications.',  keywords:'Item ScriptableObject collectible ApplyEffects effects stackable displayName image' },
  { url:'sc-equipment.html',         title:'Equipment',                   category:'Scripting', desc:'Extends Item with an equipment slot type and passive stat bonuses — Equipment.Type enum, StatValue pairs.',               keywords:'Equipment ScriptableObject slot type Weapon Shield Helmet Armor Boots twoHanded GetStatValue StatValue' },

  // ── Scripting — Level & Utility ───────────────────────
  { url:'sc-level-goals.html',        title:'LevelGoal',                   category:'Scripting', desc:'Abstract base for level challenge goals — subclass to define custom star objectives evaluated against LevelData.',      keywords:'LevelGoal goal level star Check displayText LevelData custom create InstructionCount LoopCount' },
  { url:'sc-level-manager.html',     title:'LevelManager',                category:'Scripting', desc:'Controls level lifecycle — Play, Pause, Observe, Stop and ResetLevel.',                                            keywords:'LevelManager level play pause observe stop reset transition lifecycle singleton' },
  { url:'sc-map-manager.html',       title:'MapManager',                  category:'Scripting', desc:'Tilemap utilities — world-to-cell conversion, cellSize constant and GetTile queries.',                             keywords:'MapManager map tilemap cell position cellSize GetTile world convert' },
  { url:'sc-notification.html',      title:'NotificationCenter',          category:'Scripting', desc:'Static notification bus — call Notify() to send UI feedback messages to the player.',                              keywords:'NotificationCenter notification message UI feedback static Notify MessageType' },

  // ── Scripting — Scriptable Objects ───────────────────
  { url:'sc-scriptable-objects.html', title:'IdentifiableSO',              category:'Scripting', desc:'Abstract base class for ScriptableObjects with a persistent GUID-based ID — used by Item, Equipment, and LevelInfo for save-safe asset references.',  keywords:'IdentifiableSO ScriptableObject ID GUID persistent save reference base class' },
  { url:'sc-stat.html',              title:'Stat',                         category:'Scripting', desc:'Named ScriptableObject key for a character attribute — links equipment bonuses and item effects to a shared identifier.',                          keywords:'Stat ScriptableObject displayName icon description damage defense attribute key' },
  { url:'sc-effect.html',            title:'Effect',                       category:'Scripting', desc:'Serializable stat modification embedded in Item assets — controls value, duration, and per-turn application for timed or instant stat changes.',       keywords:'Effect serializable stat modification targetStat value duration applyPerTurn regeneration damage-over-time HUD' },
  { url:'sc-items-references.html',  title:'ItemsReferences',              category:'Scripting', desc:'ScriptableObject that holds the master list of all Item assets — read by DatabaseManager at startup to build the runtime item database.',            keywords:'ItemsReferences ScriptableObject Items DatabaseManager master list Contains Add RemoveAll' },

  // ── Scripting — Audio ─────────────────────────────────
  { url:'sc-sound-manager.html',     title:'SoundManager',                category:'Scripting', desc:'Singleton for SFX playback and AudioMixer volume control via Set().',                                              keywords:'SoundManager audio SFX sound effect play mixer volume Set singleton' },
  { url:'sc-music-manager.html',     title:'MusicManager',                category:'Scripting', desc:'Singleton for background music playback with crossfade support.',                                                   keywords:'MusicManager music BGM crossfade play loop singleton' },
  { url:'sc-sound-slider.html',      title:'SoundSlider',                 category:'Scripting', desc:'UI helper that links a Unity Slider to a SoundManager AudioMixer parameter.',                                      keywords:'SoundSlider UI slider mixer volume settings audio OnValueChanged' },

  // ── Manual — UI ───────────────────────────────────────
  { url:'manual-ui.html',            title:'UI Setup',                    category:'Manual',    desc:'Configuring player and enemy HUD bars, inventory window, notifications, win screen and custom Window subclasses.', keywords:'UI HUD health stamina bar window inventory notification win screen custom Window setup' },

  // ── Scripting — Instructions (runtime) ───────────────
  { url:'sc-action.html',            title:'Action',                      category:'Scripting', desc:'MonoBehaviour bridge between an instruction C# type and its InstructionLayout prefab — lives on each draggable palette item.',     keywords:'Action instructionType layout CreateInstruction CreateLayout Load palette drag' },
  { url:'sc-instruction-sheet.html', title:'InstructionSheet',            category:'Scripting', desc:'Singleton UI manager for the instruction sheet — owns the layout list, drop handling, execution cursor, and undo/redo history.',  keywords:'InstructionSheet current singleton Insert Remove ClearSheet Undo Redo Load pointer cursor undo history' },
  { url:'sc-instruction-runner.html',title:'InstructionRunner',           category:'Scripting', desc:'Execution engine that cycles through instructions turn by turn, schedules parallel tasks, and fires success/failure events.',       keywords:'InstructionRunner Play Stop Observe Reset ExecutionStatus OnTurnStart OnTurnEnd OnSucceed OnFail TaskSchedule' },

  // ── Scripting — UI ────────────────────────────────────
  { url:'sc-window.html',            title:'Window',                      category:'Scripting', desc:'Abstract base class for all modal windows — toggles the GameObject on Open/Close and plays optional sound effects.',  keywords:'Window Open Close modal base class sound openSound closeSound subclass' },
  { url:'sc-hud.html',               title:'HUD',                         category:'Scripting', desc:'PlayerHealthBar, PlayerStaminaBar and HUD_ShowStatEffectNumber — live stat display components that auto-subscribe to LevelManager events.', keywords:'HUD health stamina bar toggle hearts pips damage floating numbers ShowNumber ShowBlockSign DefaultExecutionOrder' },
  { url:'sc-inventory-ui.html',      title:'Inventory UI',                category:'Scripting', desc:'InventoryWindow singleton, ItemSlotLayout, EquipmentSlotLayout and the floating equipment tooltip.',               keywords:'InventoryWindow inventory UI slot item equipment tooltip refresh current StatSlot Refresh ItemSlotLayout EquipmentSlotLayout' },
  { url:'sc-notification-layout.html',title:'Notifications',              category:'Scripting', desc:'NotificationLayout toast pop-up and EquipmentNotification queue for announcing new gear across scenes.',            keywords:'notification toast EquipmentNotification queue popup icon message dismiss CreateInstance AddEquipment' },
  { url:'sc-instruction-layouts.html',title:'Instruction Layouts',        category:'Scripting', desc:'InstructionLayout base widget plus Modifier, Sequence, and Use subclasses — render and manage instruction widgets on the sheet.', keywords:'InstructionLayout InstructionModifierLayout InstructionSequenceLayout InstructionUseLayout CreateInstance Remove SetDirection CycleDirection ResetLayout SyncVirtualInstruction' },
  { url:'sc-drag-drop.html',          title:'Drag & Drop',                category:'Scripting', desc:'DragAndDrop drives palette item dragging and insert-indicator updates. DropActionEventCaller is a lightweight drop zone.',          keywords:'DragAndDrop DropActionEventCaller currentDragging dragCaptured dragging leaveInstance AddDropEvent OnDrop' },
];
