window.SEARCH_INDEX = [
  // ── Manual ─────────────────────────────────────────────
  { url:'manual-levels.html',        title:'Create a Level',             category:'Manual',    desc:'How to build a new level — LevelInfo asset, scene setup, tile grid, player, LevelManager wiring, and goal configuration.',    keywords:'level create scene LevelInfo tile grid PathTile Start End LevelManager goals setup' },
  { url:'manual-overview.html',      title:'Overview',                   category:'Manual',    desc:'Project setup, asset structure, Prefabs folder, first-run guide and save/load system.',                             keywords:'setup prefabs scenes level save load execution context first run' },
  { url:'manual-instruction.html',   title:'Create an Instruction',      category:'Manual',    desc:'How to write a custom player instruction from scratch using the Instruction base class.',                           keywords:'instruction create custom move attack direction validate execute' },
  { url:'manual-instruction-layout.html', title:'Create an Instruction Layout', category:'Manual', desc:'How to duplicate, configure and wire an InstructionLayout prefab — the draggable widget that represents a player instruction on the sheet.', keywords:'instruction layout prefab Action palette drag drop InstructionLayout InstructionModifierLayout InstructionSequenceLayout InstructionUseLayout widget configure' },
  { url:'manual-enemy.html',         title:'Create an Enemy Instruction', category:'Manual',   desc:'How to write an enemy behaviour script using EnemyInstruction and the task system.',                                keywords:'enemy instruction behaviour AI create GetTask task' },
  { url:'manual-interactable.html',  title:'Create an Interactable',     category:'Manual',    desc:'How to implement IInteractable, IPushable, IPickable or IObstacle on a game object.',                              keywords:'interactable door pushable pickup obstacle IInteractable create guide' },
  { url:'manual-traps.html',         title:'Tile Traps',                  category:'Manual',    desc:'How to place and configure PressurePlate and AppearingSpikes tile traps in a level.',                                     keywords:'trap pressure plate appearing spikes tile setup stages lethal damage OnActivated OnDeactivated' },
  { url:'manual-inventory.html',     title:'Inventory System',            category:'Manual',    desc:'Setting up items, equipment and the PlayerInventory — pickup flow and stat bonuses.',                               keywords:'inventory item equipment stat pickup player setup' },
  { url:'manual-audio.html',         title:'Audio Setup',                 category:'Manual',    desc:'Configuring SoundManager, MusicManager, AudioMixer parameters and the SoundSlider UI component.',                  keywords:'audio sound music mixer SoundManager MusicManager SoundSlider setup volume' },

  // ── Scripting — Instructions ───────────────────────────
  { url:'sc-instruction.html',       title:'Instruction',                 category:'Scripting', desc:'Abstract base class for all player instructions. Override Validate() and Execute() to define behaviour.',          keywords:'Instruction abstract base class validate execute direction OnStart OnEnd' },
  { url:'sc-player-instruction.html',title:'PlayerInstruction',           category:'Scripting', desc:'Runtime pair of an Instruction and a Direction placed on the player sheet.',                                        keywords:'PlayerInstruction direction sheet runtime wrapper' },
  { url:'sc-modifier.html',          title:'InstructionModifier',         category:'Scripting', desc:'Wraps a child PlayerInstruction and overrides its direction at runtime — used for Combo branching.',               keywords:'InstructionModifier modifier direction child wrap combo' },
  { url:'sc-sequence.html',          title:'InstructionSequence',         category:'Scripting', desc:'Ordered list of PlayerInstructions executed sequentially within a single turn.',                                    keywords:'InstructionSequence sequence combo ordered list turn AddInstruction' },
  { url:'sc-sequence-layouts.html',  title:'Sequence Layout Interfaces',  category:'Scripting', desc:'Two UI interfaces for rendering and managing nested instruction sequence widgets on the player sheet.',               keywords:'sequence layout widget UI nested AddInstruction RemoveInstruction GetChild children Count' },
  { url:'sc-enemy-instruction.html', title:'EnemyInstruction',            category:'Scripting', desc:'Base class for enemy behaviours. Scheduled by the runner each turn alongside the player.',                         keywords:'EnemyInstruction enemy behaviour AI turn GetTask task runner' },
  { url:'sc-execution-context.html',    title:'ExecutionContext',            category:'Scripting', desc:'Central runtime object — holds references to player, inventory, map, carryTarget and turn interval.',               keywords:'ExecutionContext runtime player inventory map turn interval carryTarget clone' },
  { url:'sc-execution-subscriber.html', title:'IExecutionSuscriber',         category:'Scripting', desc:'Lightweight notification interface for components that react to each instruction step — auto-discovered from the player and enemy hierarchy, no manual wiring required.',  keywords:'IExecutionSuscriber subscriber execute player enemy notification auto-discover GetComponentsInChildren ShootSuscriber OnExecute' },
  { url:'sc-builtin.html',           title:'Built-in Instructions',       category:'Scripting', desc:'Reference for all built-in instructions: Move, Attack, Block, Wait, Heal and Combo types.',                       keywords:'builtin instructions Move Attack Block Wait Heal Combo PickUp Drop built-in' },
  { url:'sc-custom-instruction.html',title:'CustomInstruction',           category:'Scripting', desc:'Instruction subclass that lets you define execution behaviour entirely through delegates, without creating a new class.', keywords:'custom instruction delegate runtime tick execute coroutine one-off displayName' },
  { url:'sc-tasks.html',             title:'Tasks',                       category:'Scripting', desc:'Async task system for scheduling per-turn work alongside the player, and the receiver interface implemented by enemies.',    keywords:'task turn schedule GetTask Status Running Completed Interrupted async coroutine' },

  // ── Scripting — Interactables ──────────────────────────
  { url:'sc-iinteractable.html',     title:'IInteractable',              category:'Scripting', desc:'Marks a world object as interactable. Called by Instruction_Interact when the player interacts.',                    keywords:'IInteractable interact Validate Interact automatic OnInteract' },
  { url:'sc-icarryobject.html',      title:'ICarryObject',               category:'Scripting', desc:'Marks an object as carryable by the player. Instruction_Carry picks it up; Instruction_Drop releases it.',        keywords:'ICarryObject carry Take Drop carryable object' },
  { url:'sc-ipushable.html',         title:'IPushable',                  category:'Scripting', desc:'Marks an object as pushable. Instruction_Push moves it one tile with collision validation.',                      keywords:'IPushable push Validate Push Stop pushable' },
  { url:'sc-iobstacle.html',         title:'IObstacle',                  category:'Scripting', desc:'Tags an object as a physical blocker. Used by movement and push validation to detect walls and doors.',              keywords:'IObstacle blocking obstacle Validate blocked passable' },
  { url:'sc-execution-context-element.html', title:'ExecutionContextElement', category:'Scripting', desc:'Abstract base class for all world objects in level execution. Cloned at play start for reversible gameplay.',    keywords:'ExecutionContextElement execute clone Initialize context parent IsRoot' },
  { url:'sc-builtin-interactables.html',title:'Built-in Interactables',  category:'Scripting', desc:'Reference for all built-in world objects: doors, crates, levers, pickups and more.',                             keywords:'builtin interactable door crate lever pickup tile built-in' },
  { url:'sc-traps.html',             title:'Traps',                       category:'Scripting', desc:'Automatic turn-based tile traps that detect occupation, fire events, and deal lethal damage.',                      keywords:'trap spikes tile damage health stages appearing pressure plate turn-based events OnActivated OnDeactivated' },

  // ── Scripting — Inventory ──────────────────────────────
  { url:'sc-inventory.html',         title:'PlayerInventory',             category:'Scripting', desc:'Singleton inventory — add/remove items, query equipped gear and get stat totals.',                                  keywords:'PlayerInventory inventory singleton item equipment stat Add Remove GetStatValue' },
  { url:'sc-items.html',             title:'Item',                        category:'Scripting', desc:'Base ScriptableObject for collectible items — display name, icon, stackable flag, and ApplyEffects for stat modifications.',  keywords:'Item ScriptableObject collectible ApplyEffects effects stackable displayName image' },
  { url:'sc-equipment.html',         title:'Equipment',                   category:'Scripting', desc:'ScriptableObject that extends Item with an equipment slot type and passive stat bonuses.',                              keywords:'Equipment ScriptableObject slot type Weapon Shield Helmet Armor Boots twoHanded GetStatValue' },

  // ── Scripting — Level & Utility ───────────────────────
  { url:'sc-level-goals.html',        title:'LevelGoal',                   category:'Scripting', desc:'Abstract base for level challenge goals — subclass to define custom star objectives for evaluating player performance.',  keywords:'LevelGoal goal level star Check displayText custom create InstructionCount LoopCount' },
  { url:'sc-level-manager.html',     title:'LevelManager',                category:'Scripting', desc:'Controls level lifecycle — Play, Pause, Observe, Stop and ResetLevel.',                                            keywords:'LevelManager level play pause observe stop reset transition lifecycle singleton' },
  { url:'sc-map-manager.html',       title:'MapManager',                  category:'Scripting', desc:'Tilemap utilities — world-to-cell conversion, cellSize constant and GetTile queries.',                             keywords:'MapManager map tilemap cell position cellSize GetTile world convert' },
  { url:'sc-notification.html',      title:'NotificationCenter',          category:'Scripting', desc:'Static notification bus — call Notify() to send UI feedback messages to the player.',                              keywords:'NotificationCenter notification message UI feedback static Notify MessageType' },

  // ── Scripting — Scriptable Objects ───────────────────
  { url:'sc-scriptable-objects.html', title:'IdentifiableSO',              category:'Scripting', desc:'Abstract base class for ScriptableObjects with a persistent GUID-based ID — used by Item, Equipment, and LevelInfo for save-safe asset references.',  keywords:'IdentifiableSO ScriptableObject ID GUID persistent save reference base class' },
  { url:'sc-stat.html',              title:'Stat',                         category:'Scripting', desc:'Named ScriptableObject key for a character attribute — links equipment bonuses and item effects to a shared identifier.',                          keywords:'Stat ScriptableObject displayName icon description damage defense attribute key' },
  { url:'sc-effect.html',            title:'Effect',                       category:'Scripting', desc:'Serializable stat modification embedded in Item assets — controls value, duration, and per-turn application for timed or instant stat changes.',       keywords:'Effect serializable stat modification targetStat value duration applyPerTurn regeneration damage-over-time HUD' },
  { url:'sc-items-references.html',  title:'ItemsReferences',              category:'Scripting', desc:'ScriptableObject that holds the master list of all Item assets — read by DatabaseManager at startup to build the runtime item database.',            keywords:'ItemsReferences ScriptableObject Items DatabaseManager master list Contains Add RemoveAll' },

  // ── Scripting — Audio ─────────────────────────────────
  { url:'sc-sound-manager.html',     title:'SoundManager',                category:'Scripting', desc:'Singleton for SFX playback and AudioMixer volume control via Set().',                                              keywords:'SoundManager audio SFX sound effect play mixer volume Set singleton' },
  { url:'sc-music-manager.html',     title:'MusicManager',                category:'Scripting', desc:'Singleton for background music playback with crossfade support.',                                                   keywords:'MusicManager music BGM crossfade play loop singleton' },
  { url:'sc-sound-slider.html',      title:'SoundSlider',                 category:'Scripting', desc:'UI helper that links a Unity Slider to a SoundManager AudioMixer parameter.',                                      keywords:'SoundSlider UI slider mixer volume settings audio OnValueChanged' },

  // ── Manual — UI ───────────────────────────────────────
  { url:'manual-ui.html',            title:'UI Setup',                    category:'Manual',    desc:'Configuring player and enemy HUD bars, inventory window, notifications, win screen and custom Window subclasses.', keywords:'UI HUD health stamina bar window inventory notification win screen custom Window setup' },

  // ── Scripting — Instructions (runtime) ───────────────
  { url:'sc-action.html',            title:'Action',                      category:'Scripting', desc:'MonoBehaviour bridge between an instruction C# type and its InstructionLayout prefab — lives on each draggable palette item.',     keywords:'Action instructionType layout CreateInstruction CreateLayout Load palette drag' },
  { url:'sc-instruction-sheet.html', title:'InstructionSheet',            category:'Scripting', desc:'Singleton UI manager for the instruction sheet — owns the layout list, drop handling, execution cursor, and undo/redo history.',  keywords:'InstructionSheet current singleton Insert Remove ClearSheet Undo Redo Load pointer cursor undo history' },
  { url:'sc-instruction-runner.html',title:'InstructionRunner',           category:'Scripting', desc:'Execution engine that cycles through instructions turn by turn, schedules parallel tasks, and fires success/failure events.',       keywords:'InstructionRunner Play Stop Observe Reset ExecutionStatus OnTurnStart OnTurnEnd OnSucceed OnFail TaskSchedule' },

  // ── Scripting — UI ────────────────────────────────────
  { url:'sc-window.html',            title:'Window',                      category:'Scripting', desc:'Abstract base class for all modal windows — toggles the GameObject on Open/Close and plays optional sound effects.',  keywords:'Window Open Close modal base class sound openSound closeSound subclass' },
  { url:'sc-hud.html',               title:'HUD',                         category:'Scripting', desc:'Live stat display components that auto-subscribe to LevelManager events — health hearts, stamina pips, a stat panel, and floating damage/heal numbers.', keywords:'HUD health stamina bar toggle hearts pips damage floating numbers ShowNumber ShowBlockSign DefaultExecutionOrder' },
  { url:'sc-inventory-ui.html',      title:'Inventory UI',                category:'Scripting', desc:'Full-screen inventory window, item and equipment slot widgets, and a floating equipment tooltip — all live-update on inventory changes.',               keywords:'inventory UI slot item equipment tooltip refresh current StatSlot Refresh' },
  { url:'sc-instruction-layout.html',    title:'InstructionLayout',           category:'Scripting', desc:'Base widget class for rendering instructions on the instruction sheet. Handles line numbers, loops, directions, and drag operations.',            keywords:'InstructionLayout base widget instruction sheet CreateInstance Load Remove IncreaseLoop DecreaseLoop SetDirection CycleDirection' },
  { url:'sc-instruction-modifier-layout.html', title:'InstructionModifierLayout', category:'Scripting', desc:'Widget for InstructionModifier subclasses. Extends InstructionLayout to add a child instruction drop zone.',  keywords:'InstructionModifierLayout modifier child instruction drop zone SetInstruction SetDirection' },
  { url:'sc-instruction-sequence-layout.html', title:'InstructionSequenceLayout', category:'Scripting', desc:'Widget for InstructionSequence subclasses (Combo, Ping Pong). Manages nested child layouts and implements IInstructionSequenceLayout.',  keywords:'InstructionSequenceLayout sequence nested children combo AddInstruction RemoveInstruction Insert' },
  { url:'sc-instruction-use-layout.html',     title:'InstructionUseLayout',     category:'Scripting', desc:'Widget for the Use instruction. Extends InstructionLayout with an item picker button for selecting consumable items.',   keywords:'InstructionUseLayout Use instruction item picker OpenInventory SetItem LoadItem' },
  { url:'sc-notification-layout-ui.html',    title:'NotificationLayout',       category:'Scripting', desc:'Generic toast notification that displays an icon and message for 7 seconds, then auto-dismisses.',                     keywords:'notification toast popup icon message dismiss CreateInstance Close timer unscaled' },
  { url:'sc-equipment-notification.html',    title:'EquipmentNotification',     category:'Scripting', desc:'Persistent notification panel that queues equipment announcements with stats and effects across scene loads.',          keywords:'EquipmentNotification equipment notification queue panel globe stats effects AddEquipment ActivateGlobe' },
  { url:'sc-drag-and-drop.html',             title:'DragAndDrop',              category:'Scripting', desc:'Implements drag-and-drop handlers to enable instruction reordering. Manages ghost copies and cursor following.',      keywords:'DragAndDrop drag drop instruction reordering ghost cursor currentDragging dragCaptured dragging leaveInstance' },
  { url:'sc-drop-action-event-caller.html',  title:'DropActionEventCaller',    category:'Scripting', desc:'Lightweight drop zone for accepting dragged instructions and invoking callbacks.',                                   keywords:'DropActionEventCaller drop zone lightweight instruction callback AddDropEvent OnDrop IDropHandler' },

  // ── Scripting — Components ────────────────────────────
  { url:'sc-character-instance-controller.html', title:'CharacterInstanceController', category:'Scripting', desc:'Abstract base class for all character entities. Provides animation, audio, health, directional sprite flipping, and blocking state. Subclass to add a new character type.', keywords:'CharacterInstanceController abstract base character animation audio health direction blocking damage defense SetDirection PlayAnimation Initialize OnInitialize ExecutionContextElement player enemy subclass' },
  { url:'sc-player-controller.html', title:'PlayerController', category:'Scripting', desc:'Root MonoBehaviour for the player prefab. Manages inventory-driven damage and defense stats, stamina, item usage visual effects, audio, and tile position validation.', keywords:'PlayerController player root MonoBehaviour stamina damage defense UseItem ValidatePosition OnExecute Initialize damageStat defenseStat useItemFX useItemParticles CharacterInstanceController ActiveEffectsController' },
  { url:'sc-enemy-controller.html',  title:'EnemyController',  category:'Scripting', desc:'Root MonoBehaviour for enemy prefabs. Controls patrol routing, player detection, attack-sequence cycling, hover highlighting of attack range tiles, and IObstacle blocking.', keywords:'EnemyController enemy root MonoBehaviour patrol detection attack sequence IObstacle ITaskReceiver GetTask moveSequence attackSequence EnemyActionInstance OnActionChange OnExecute OnMouseHover range directions blocking CharacterInstanceController' },
  { url:'sc-player-stamina.html',     title:'PlayerStamina',               category:'Scripting', desc:'Tracks the player stamina resource with events for HUD display and methods to spend or restore points from instructions.',          keywords:'PlayerStamina stamina Substract Add OnDepleted OnReplenished OnInitialize OnValueUpdated stat player resource' },
  { url:'sc-health.html',             title:'Health',                      category:'Scripting', desc:'Abstract health base class with damage, block, heal, and kill methods. Subclassed for player and enemy specific behaviour.', keywords:'Health ApplyDamage Heal Kill OnDie OnDamageApplied OnDamageBlocked maxHealth currentHealth blocking defense abstract' },
  { url:'sc-active-effects-controller.html', title:'ActiveEffectsController', category:'Scripting', desc:'Tracks all active timed stat effects on the player, decrements their remaining turns each turn, and reverts them on expiry.', keywords:'ActiveEffectsController timed effect duration Track Clear revert stat expires turns active' },
  { url:'sc-enemy-hud.html',          title:'Enemy HUD',                   category:'Scripting', desc:'Five components for the in-world enemy display: a stat panel on hover, health counter, animated action indicator, full action-sequence panel, and per-action layout widget.', keywords:'enemy HUD health indicator sequence panel icon loops stats hover' },
  { url:'sc-item-dropper.html',       title:'ItemDropper',                 category:'Scripting', desc:'Spawns a pickup at the entity tile position on death. Includes a visual effect component that briefly flashes an item sprite at the use position.',           keywords:'ItemDropper Drop pickup loot spawn death OnDie InteractableObject_Pickup sprite flash CreatInstance' },
  { url:'sc-game-data-manager.html',  title:'GameDataManager',             category:'Scripting', desc:'Singleton that persists level progress, audio settings, and discovered equipment. All members are static — no instance reference needed.', keywords:'GameDataManager SaveLevel GetLevelData SaveSoundSetting GetSoundSetting GetAllSoundSettings SaveNow AddDiscoveredEquipment DiscoveredEquipment singleton save persist' },
  { url:'sc-database-manager.html',   title:'DatabaseManager',             category:'Scripting', desc:'Singleton that indexes every item asset from an ItemsReferences asset into fast type-specific lookup tables at startup.',           keywords:'DatabaseManager current singleton ItemsReferences items database lookup type index startup' },
  { url:'sc-world-map.html',          title:'World Map',                   category:'Scripting', desc:'Two components powering the world map scene — map initialization, level unlock chaining, and star rating display.', keywords:'world map unlock progression stars level active scene' },
  { url:'sc-level-screens.html',      title:'Level Screens',               category:'Scripting', desc:'UI screens for level selection, win results, in-game options, and item selection — displayed before and after gameplay.', keywords:'level screens UI Open Close PlayLevel ResetLevel GoToWorldMap' },
  { url:'sc-equipment-browser.html',  title:'Equipment Browser',           category:'Scripting', desc:'Paginated list of discovered equipment with individual entry widgets and stat/effect display rows for equipment tooltips.', keywords:'equipment browser paginated ShowType Next Previous CreateInstance discovered' },
  { url:'sc-projectile.html',         title:'Projectile',                  category:'Scripting', desc:'Self-propelled component that travels in a straight line and applies damage on impact. Fire with Shoot() from an instruction or via ShootSuscriber on enemies.', keywords:'Projectile Shoot speed damage shootSound hitSound Initialize direction ranged ShootSuscriber enemy' },
  { url:'sc-visual-fx.html',          title:'Visual FX',                   category:'Scripting', desc:'Drop-in visual effect components — breathing animations for sprites and UI, hover scale for buttons, and procedural drifting clouds.', keywords:'visual FX breathing pulse hover scale clouds sine wave speed amplitude' },
  { url:'sc-utility-components.html', title:'Utilities',                   category:'Scripting', desc:'Drop-in utility components — UI state locking during play, pixel and grid snapping, and Y-based painter depth sorting.', keywords:'utility disable running CanvasGroup button pixel snap grid Y sorting depth' },

  // ── Manual — Setup Guides ─────────────────────────────
  { url:'manual-player-setup.html',      title:'Player Setup',             category:'Manual',    desc:'Configure health, stamina, and active effects on the player GameObject and wire each component to the HUD.', keywords:'player setup PlayerStamina ActiveEffectsController HUD health stamina wiring events' },
  { url:'manual-enemy-setup.html',       title:'Enemy Setup',              category:'Manual',    desc:'Configure enemy health, optional loot drop, and the four enemy HUD components on an enemy prefab.',          keywords:'enemy setup ItemDropper HUD prefab health' },
  { url:'manual-data-systems.html',      title:'Data Systems',             category:'Manual',    desc:'Set up DatabaseManager and GameDataManager as persistent singletons. Save and read level progress and discovered equipment.',keywords:'data systems DatabaseManager GameDataManager save load level progress discovered equipment persistent singleton setup' },
  { url:'manual-world-map-setup.html',   title:'World Map',                category:'Manual',    desc:'Build the world map scene with level nodes chained for unlock progression and star ratings.',  keywords:'world map setup unlock chain stars progression scene nodes' },
  { url:'manual-ui-screens.html',        title:'UI Screens',               category:'Manual',    desc:'Configure the win screen, options menu, and item list window. All extend Window and follow the same open/close pattern.',keywords:'UI screens Window Open Close setup level win options items' },
  { url:'manual-projectile-setup.html',  title:'Projectile',               category:'Manual',    desc:'Create a projectile prefab and fire it from a ranged instruction or attach ShootSuscriber to an enemy.',               keywords:'projectile setup Projectile Shoot ShootSuscriber ranged prefab speed damage instruction enemy' },
  { url:'manual-visual-fx-setup.html',   title:'Visual FX & Utilities',    category:'Manual',    desc:'Drop-in components for breathing animations, hover effects, clouds, UI state locking during play, pixel snapping, and depth sorting.', keywords:'visual FX utilities breathing hover clouds pixel snap depth animation' },

  // ── Individual class entries for shared-page classes ─────
  // sc-enemy-hud.html
  { url:'sc-enemy-hud.html#enemy-stats-container',       title:'EnemyStatsContainer',          category:'Scripting', desc:'HUD panel inside the enemy prefab that shows stat rows (damage, defence, extras) visible on mouse hover.', keywords:'EnemyStatsContainer enemy HUD stats panel hover damage defence statLayoutPrefab container Initialize' },
  { url:'sc-enemy-hud.html#enemy-health-bar',            title:'EnemyHealthBar',               category:'Scripting', desc:'Displays the enemy current health as a live text counter. Subscribes automatically to EnemyHealth events.', keywords:'EnemyHealthBar enemy health counter HUD healthCounter text label' },
  { url:'sc-enemy-hud.html#enemy-instruction-indicator', title:'EnemyInstructionIndicator',    category:'Scripting', desc:'Animated icon display that transitions between the enemy current and previous actions using an Animator.', keywords:'EnemyInstructionIndicator enemy action icon animated transition Animator entry exit Initialize' },
  { url:'sc-enemy-hud.html#enemy-action-sequence-panel', title:'EnemyActionSequencePanel',     category:'Scripting', desc:'Renders the enemy full attack sequence as a grid of action icons with loop counts. Populated on Initialize.', keywords:'EnemyActionSequencePanel enemy attack sequence panel icons loop Initialize EnemyAction_Layout' },
  { url:'sc-enemy-hud.html#enemy-action-layout',         title:'EnemyAction_Layout',           category:'Scripting', desc:'Single entry widget in the EnemyActionSequencePanel — shows one action icon and its loop count.', keywords:'EnemyAction_Layout enemy action icon loop count widget CreateInstance layout' },

  // sc-hud.html
  { url:'sc-hud.html#player-health-bar',           title:'PlayerHealthBar',           category:'Scripting', desc:'Renders player HP as a row of heart Toggle widgets. Auto-subscribes to LevelManager and health events.', keywords:'PlayerHealthBar health bar hearts toggle HUD player heartPrefab healthContainer Initialize Reset' },
  { url:'sc-hud.html#player-stamina-bar',          title:'PlayerStaminaBar',          category:'Scripting', desc:'Renders player stamina as a row of pip Toggle widgets. Follows the same event subscription pattern as PlayerHealthBar.', keywords:'PlayerStaminaBar stamina bar pips toggle HUD player pointPrefab container Initialize Reset' },
  { url:'sc-hud.html#player-stats',                title:'PlayerStats',               category:'Scripting', desc:'HUD panel that displays the player damage, defence, and additional stats as icon-value rows. Populated on Start.', keywords:'PlayerStats player HUD stats damage defence icon value panel container statPrefab StatElement_Layout' },
  { url:'sc-hud.html#hud-show-stat-effect-number', title:'HUD_ShowStatEffectNumber',  category:'Scripting', desc:'Floating number that appears above a character when damage, healing or a block event fires. Attach as a child of any Health or PlayerStamina owner.', keywords:'HUD_ShowStatEffectNumber floating number damage heal block ShowNumber ShowBlockSign negativeColor positiveColor blockedColor' },

  // sc-builtin-interactables.html
  { url:'sc-builtin-interactables.html#pickup',          title:'InteractableObject_Pickup',          category:'Scripting', desc:'Pick-up item world object — collected by moving onto its tile or using Instruction_Interact. Fires OnInteract.', keywords:'InteractableObject_Pickup pickup collect item tile IInteractable Interact automatic' },
  { url:'sc-builtin-interactables.html#chest',           title:'InteractableObject_Chest',           category:'Scripting', desc:'Chest that yields a random item from a weighted loot table when opened by the player.', keywords:'InteractableObject_Chest chest loot item random open IInteractable' },
  { url:'sc-builtin-interactables.html#carry',           title:'InteractableObject_Carry',           category:'Scripting', desc:'Carryable object the player can pick up, move around, and drop using the Carry and Drop instructions.', keywords:'InteractableObject_Carry carry drop ICarryObject Take Drop player instruction' },
  { url:'sc-builtin-interactables.html#pushable-object', title:'InteractableObject_PushableObject',  category:'Scripting', desc:'Pushable object that slides one tile in the push direction after passing IObstacle validation.', keywords:'InteractableObject_PushableObject pushable push slide IPushable Validate Stop tile' },
  { url:'sc-builtin-interactables.html#door',            title:'InteractableObject_Door',            category:'Scripting', desc:'Door that acts as an IObstacle when closed and clears the obstacle flag when opened via IInteractable.', keywords:'InteractableObject_Door door IObstacle IInteractable open close blocking Validate' },

  // sc-equipment-browser.html
  { url:'sc-equipment-browser.html#discovered-equipment-list',   title:'DiscoveredEquipmentList',    category:'Scripting', desc:'Paginated list of all equipment the player has discovered. Use ShowType to filter by slot and Next/Previous to page.', keywords:'DiscoveredEquipmentList paginated equipment discovered list ShowType Next Previous graphic container maxPerLot' },
  { url:'sc-equipment-browser.html#discovered-equipment-layout', title:'DiscoveredEquipment_Layout', category:'Scripting', desc:'Single equipment entry widget in the DiscoveredEquipmentList panel. Shows name, icon, and equipped state.', keywords:'DiscoveredEquipment_Layout equipment entry widget layout CreateInstance icon equippedFrame' },
  { url:'sc-equipment-browser.html#stat-element-layout',         title:'StatElement_Layout',         category:'Scripting', desc:'Icon-value row UI element for displaying a single stat. Use CreateInstance or Set to configure it from a StatValue.', keywords:'StatElement_Layout stat element icon value row UI CreateInstance Set Get StatValue' },
  { url:'sc-equipment-browser.html#effect-element-layout',       title:'EffectElement_Layout',       category:'Scripting', desc:'Icon-value row UI element for displaying a single item effect in the equipment tooltip.', keywords:'EffectElement_Layout effect element icon value row UI layout equipment tooltip' },

  // sc-inventory-ui.html
  { url:'sc-inventory-ui.html#inventory-window',              title:'InventoryWindow',              category:'Scripting', desc:'Singleton full-screen inventory window showing equipment slots, item slots, and stat totals. Extends Window.', keywords:'InventoryWindow singleton inventory window Open Close Refresh equipment item slot stats current' },
  { url:'sc-inventory-ui.html#item-slot-layout',              title:'ItemSlotLayout',               category:'Scripting', desc:'UI widget for a single item slot. Shows the item icon and stack count; updates on inventory change events.', keywords:'ItemSlotLayout item slot widget icon count inventory UI update SetItem OnSelectItem' },
  { url:'sc-inventory-ui.html#equipment-slot-layout',         title:'EquipmentSlotLayout',          category:'Scripting', desc:'UI widget for a single equipment slot. Shows equipped item icon; handles equip/unequip interaction.', keywords:'EquipmentSlotLayout equipment slot widget icon equip unequip UI inventory type' },
  { url:'sc-inventory-ui.html#equipment-slot-tooltip-layout', title:'EquipementSlot_TooltipLayout', category:'Scripting', desc:'Floating tooltip shown on hover over an equipment slot. Displays the equipped item stats and effects.', keywords:'EquipementSlot_TooltipLayout tooltip equipment slot hover stats effects floating UI Show Hide current' },

  // sc-utility-components.html
  { url:'sc-utility-components.html#disable-on-running',        title:'DisableOnRunning',        category:'Scripting', desc:'Dims a CanvasGroup to half opacity and blocks interaction while the instruction runner is active.', keywords:'DisableOnRunning CanvasGroup alpha opacity disable running Enable Disable LevelManager' },
  { url:'sc-utility-components.html#disable-button-on-running', title:'DisableButtonOnRunning',  category:'Scripting', desc:'Toggles a Button interactability while the instruction runner is active. Lighter alternative to DisableOnRunning.', keywords:'DisableButtonOnRunning Button interactable disable running Enable Disable LevelManager' },
  { url:'sc-utility-components.html#pixel-snaper',              title:'PixelSnaper',             category:'Scripting', desc:'Snaps this transform position to the nearest pixel or grid-cell centre every frame in both edit mode and runtime.', keywords:'PixelSnaper pixel snap grid cell transform position pixelsPerUnit cellSize snapToGrid ExecuteInEditMode' },
  { url:'sc-utility-components.html#depth-sorting-order',       title:'DepthSortingOrder',       category:'Scripting', desc:'Sets the SpriteRenderer sortingOrder each frame based on the Y position, producing painter-algorithm depth sorting.', keywords:'DepthSortingOrder depth sort Y position SpriteRenderer sortingOrder painter algorithm topLimit' },

  // sc-visual-fx.html
  { url:'sc-visual-fx.html#sprite-expand-animation', title:'SpriteExpandAnimation', category:'Scripting', desc:'Animates a SpriteRenderer size with a sine wave producing a breathing or pulsing effect on world sprites.', keywords:'SpriteExpandAnimation sprite breathing pulse sine wave speed amplitude horizontal vertical SpriteRenderer' },
  { url:'sc-visual-fx.html#sin-expand-animation',    title:'SinExpandAnimation',    category:'Scripting', desc:'Animates a RectTransform size with a sine wave, producing a UI breathing effect on canvas elements.', keywords:'SinExpandAnimation RectTransform UI breathing pulse sine wave speed amplitude horizontal vertical canvas' },
  { url:'sc-visual-fx.html#hovering-mouse',          title:'HoveringMouse',         category:'Scripting', desc:'Scales a RectTransform up slightly on pointer enter and back on exit, giving buttons a hover-zoom feel.', keywords:'HoveringMouse hover scale RectTransform pointer enter exit zoom button UI maxSize' },
  { url:'sc-visual-fx.html#clouds-controller',       title:'CloudsController',      category:'Scripting', desc:'Procedurally drifts sprite cloud instances across the screen and recycles them when they leave the view.', keywords:'CloudsController clouds procedural drift sprites recycle scroll background visual prefabs amount' },

  // sc-level-screens.html
  { url:'sc-level-screens.html#level-info-screen',     title:'LevelInfoScreen',     category:'Scripting', desc:'Screen shown on the world map when the player selects a level. Displays name, star progress and goal list.', keywords:'LevelInfoScreen level info screen world map stars goals LevelGoalLayout goalLayout levelNameText Open PlayLevel' },
  { url:'sc-level-screens.html#level-goal-layout',     title:'LevelGoalLayout',     category:'Scripting', desc:'Single goal entry widget used inside LevelInfoScreen to show each goal description and completion status.', keywords:'LevelGoalLayout goal layout widget entry description status CreateInstance LevelInfoScreen completedCheck' },
  { url:'sc-level-screens.html#win-screen-controller', title:'WinScreenController', category:'Scripting', desc:'Win screen shown on level success. Displays stars earned and provides buttons for replay and world map navigation.', keywords:'WinScreenController win screen success stars replay ResetLevel GoToWorldMap Window' },
  { url:'sc-level-screens.html#game-options-menu',     title:'GameOptionsMenu',     category:'Scripting', desc:'In-game pause/options menu. Provides Reset and Exit buttons wired to LevelManager and SceneManager.', keywords:'GameOptionsMenu options menu pause reset exit LevelManager SceneManager in-game GoToWorldMap' },
  { url:'sc-level-screens.html#items-list-window',     title:'ItemsListWindow',     category:'Scripting', desc:'Scrollable popup window that lists available items. Used by interactables that let the player choose an item.', keywords:'ItemsListWindow items list window popup scrollable interactable choose item select Open Close' },

  // sc-inventory.html — secondary classes (PlayerInventory already has its own entry)
  { url:'sc-inventory.html#inventory-preset', title:'InventoryPreset', category:'Scripting', desc:'ScriptableObject that defines a starting loadout — a fixed set of items and equipment applied to a fresh PlayerInventory.', keywords:'InventoryPreset inventory preset ScriptableObject starting loadout items equipment inventoryCapacity startingItems' },
  { url:'sc-inventory.html#inventory-data',   title:'InventoryData',   category:'Scripting', desc:'Serializable snapshot of a PlayerInventory used by the save system to persist and restore the player loadout.', keywords:'InventoryData inventory data serializable snapshot save restore persist loadout slots equipment' },

  // sc-item-dropper.html — secondary class (ItemDropper already has its own entry)
  { url:'sc-item-dropper.html#item-used-fx',  title:'ItemUsedFX',      category:'Scripting', desc:'Briefly flashes an item sprite at the player position when an item is used. Spawned by PlayerController.UseItem().', keywords:'ItemUsedFX item used FX sprite flash player position UseItem visual effect CreatInstance' },

  // sc-level-goals.html — secondary class (LevelGoal already has its own entry)
  { url:'sc-level-goals.html#level-data',     title:'LevelData',       category:'Scripting', desc:'Serializable record of one completed run — stores instruction count, loop count, and goal completion flags for the save system.', keywords:'LevelData level data save record instructions loops goals completion flags serializable playerHealth playerStamina' },

  // sc-traps.html
  { url:'sc-traps.html#pressure-plate',   title:'Tile_Interactable_PressurePlate',  category:'Scripting', desc:'Detects when the player or any obstacle stands on its tile and fires OnActivated and OnDeactivated events.', keywords:'Tile_Interactable_PressurePlate pressure plate trap tile detection OnActivated OnDeactivated occupation ITaskReceiver' },
  { url:'sc-traps.html#appearing-spikes', title:'Tile_Interactable_AppearingSpikes', category:'Scripting', desc:'Cycles through configurable stages each turn. On spike stages deals lethal damage to any Health component on the tile.', keywords:'Tile_Interactable_AppearingSpikes appearing spikes trap tile damage lethal stages turn cycle Health ITaskReceiver' },

  // sc-world-map.html
  { url:'sc-world-map.html#world-map-manager', title:'WorldMapManager', category:'Scripting', desc:'Placed once in the world map scene. Finds all level marker instances on start, initializes them, and locks markers for unavailable levels.', keywords:'WorldMapManager world map manager initialize markers lock available OpenLevelInfoScreen' },
  { url:'sc-world-map.html#level-marker',      title:'LevelMarker',     category:'Scripting', desc:'Selectable level node on the world map. Shows star rating, handles unlock chaining to child markers, and opens the level info screen.', keywords:'LevelMarker level marker world map node selectable stars unlock chain childs OpenLevelInfoScreen Initialize CheckCompleted' },

  // sc-health.html
  { url:'sc-health.html#playerhealth', title:'PlayerHealth', category:'Scripting', desc:'Extends Health with player-specific behaviour — blocks damage when the player is in a blocking pose.', keywords:'PlayerHealth player health blocking pose damage block die character' },
  { url:'sc-health.html#enemyhealth',  title:'EnemyHealth',  category:'Scripting', desc:'Extends Health with enemy-specific behaviour — factors in the enemy defence stat and fires OnDie for loot spawning.', keywords:'EnemyHealth enemy health defense stat OnDie loot death character blocking' },

  // sc-tasks.html
  { url:'sc-tasks.html#task',          title:'Task',          category:'Scripting', desc:'Wraps a single instruction execution as a coroutine. Start, Stop, or Interrupt it and listen to OnStart and OnEnd for lifecycle events.', keywords:'Task coroutine instruction execution Start Stop Interrupt OnStart OnEnd status Running Completed Interrupted GetTask' },
  { url:'sc-tasks.html#itaskreceiver', title:'ITaskReceiver', category:'Scripting', desc:'Interface implemented by enemies and NPCs that own a per-turn task. Discovered and registered automatically with ExecutionContext at initialization.', keywords:'ITaskReceiver task receiver interface enemy NPC per-turn GetTask currentInstruction OnActionChange register automatic' },

  // sc-sequence-layouts.html
  { url:'sc-sequence-layouts.html#iinstructionsequencelayout', title:'IInstructionSequenceLayout', category:'Scripting', desc:'UI widget interface for rendering and managing a list of nested instruction cards on the instruction sheet.', keywords:'IInstructionSequenceLayout sequence layout UI widget nested AddInstruction RemoveInstruction Insert GetChild Childrens Count lastSibling' },
  { url:'sc-sequence-layouts.html#inestedinstructionlayout',   title:'INestedInstructionLayout',   category:'Scripting', desc:'Single instruction card nested inside an IInstructionSequenceLayout. Bridges the visual widget and the underlying PlayerInstruction.', keywords:'INestedInstructionLayout nested instruction card widget PlayerInstruction container ResetLayout gameObject' },

  // sc-equipment.html
  { url:'sc-equipment.html#equipment-type', title:'Equipment.Type', category:'Scripting', desc:'Enum controlling which inventory slot an Equipment occupies: Weapon, Shield, Helmet, Armor, or Boots.', keywords:'Equipment.Type enum slot Weapon Shield Helmet Armor Boots twoHanded inventory occupation' },
  { url:'sc-equipment.html#statvalue',      title:'StatValue',      category:'Scripting', desc:'Serializable class pairing a Stat asset with a numeric bonus. Used in Equipment stats lists and by PlayerController and EnemyController for HUD stat display.', keywords:'StatValue stat value serializable bonus pair numeric equipment player enemy HUD stats panel' },
];
