window.SEARCH_INDEX = [
  // ── Manual ─────────────────────────────────────────────
  { url:'manual-levels.html',        title:'Create a Level',             category:'Manual',    desc:'How to build a new level — LevelInfo asset, scene setup, tile grid, player, LevelManager wiring, and goal configuration.',    keywords:'level create scene LevelInfo tile grid PathTile Start End LevelManager goals setup' },
  { url:'manual-overview.html',      title:'Overview',                   category:'Manual',    desc:'Project setup, asset structure, Prefabs folder, first-run guide and save/load system.',                             keywords:'setup prefabs scenes level save load execution context first run' },
  { url:'manual-instruction.html',   title:'Create an Instruction',      category:'Manual',    desc:'How to write a custom player instruction from scratch using the Instruction base class.',                           keywords:'instruction create custom move attack direction validate execute' },
  { url:'manual-instruction-layout.html', title:'Create an Instruction Layout', category:'Manual', desc:'How to duplicate, configure and wire an InstructionLayout prefab — the draggable widget that represents a player instruction on the sheet.', keywords:'instruction layout prefab Action palette drag drop InstructionLayout InstructionModifierLayout InstructionSequenceLayout InstructionUseLayout widget configure' },
  { url:'manual-enemy.html',         title:'Create an Enemy Instruction', category:'Manual',   desc:'How to write an enemy behaviour script using EnemyInstruction and the task system.',                                keywords:'enemy instruction behaviour AI create GetTask task' },
  { url:'manual-interactable.html',  title:'Create an Interactable',     category:'Manual',    desc:'How to implement IInteractable, IPushable, IPickable or IObstacle on a game object.',                              keywords:'interactable door pushable pickup obstacle IInteractable create guide' },
  { url:'manual-traps.html',         title:'Tile Traps',                  category:'Manual',    desc:'How to place and configure PressurePlate and AppearingSpikes tile traps in a level.',                                     keywords:'trap pressure plate appearing spikes tile setup stages lethal damage OnActivated OnDeactivated' },
  { url:'manual-inventory.html',     title:'Inventory System',            category:'Manual',    desc:'Setting up items, equipment and the PlayerInventory — pickup flow and stat bonuses.',                               keywords:'inventory item equipment stat pickup player setup' },
  { url:'manual-audio.html',         title:'Audio Setup',                 category:'Manual',    desc:'Configuring SoundManager, MusicManager, AudioMixer parameters and the SoundSlider UI component.',                  keywords:'audio sound music mixer SoundManager MusicManager SoundSlider setup volume' },

  // ── Scripting — Instructions ───────────────────────────
  { url:'sc-instruction.html',       title:'Instruction',                 category:'Scripting', desc:'Abstract base class for all player instructions. Override Validate() and Execute() to define behaviour.',          keywords:'Instruction abstract base class validate execute direction OnStart OnEnd' },
  { url:'sc-player-instruction.html',title:'PlayerInstruction',           category:'Scripting', desc:'Runtime pair of an Instruction and a Direction placed on the player sheet.',                                        keywords:'PlayerInstruction direction sheet runtime wrapper' },
  { url:'sc-modifier.html',          title:'InstructionModifier',         category:'Scripting', desc:'Wraps a child PlayerInstruction and overrides its direction at runtime — used for Combo branching.',               keywords:'InstructionModifier modifier direction child wrap combo' },
  { url:'sc-sequence.html',          title:'InstructionSequence',         category:'Scripting', desc:'Ordered list of PlayerInstructions executed sequentially within a single turn.',                                    keywords:'InstructionSequence sequence combo ordered list turn AddInstruction' },
  { url:'sc-sequence-layouts.html',  title:'Sequence Layout Interfaces',  category:'Scripting', desc:'IInstructionSequenceLayout and INestedInstructionLayout — UI widgets for rendering nested instruction sequences.',   keywords:'IInstructionSequenceLayout INestedInstructionLayout sequence layout widget UI' },
  { url:'sc-enemy-instruction.html', title:'EnemyInstruction',            category:'Scripting', desc:'Base class for enemy behaviours. Scheduled by the runner each turn alongside the player.',                         keywords:'EnemyInstruction enemy behaviour AI turn GetTask task runner' },
  { url:'sc-execution-context.html',    title:'ExecutionContext',            category:'Scripting', desc:'Central runtime object — holds references to player, inventory, map, carryTarget and turn interval.',               keywords:'ExecutionContext runtime player inventory map turn interval carryTarget clone' },
  { url:'sc-execution-subscriber.html', title:'IExecutionSuscriber',         category:'Scripting', desc:'Lightweight notification interface for components that react to each instruction step — auto-discovered from the player and enemy hierarchy, no manual wiring required.',  keywords:'IExecutionSuscriber subscriber execute player enemy notification auto-discover GetComponentsInChildren ShootSuscriber OnExecute' },
  { url:'sc-builtin.html',           title:'Built-in Instructions',       category:'Scripting', desc:'Reference for all built-in instructions: Move, Attack, Block, Wait, Heal and Combo types.',                       keywords:'builtin instructions Move Attack Block Wait Heal Combo PickUp Drop built-in' },
  { url:'sc-custom-instruction.html',title:'Custom Instructions',         category:'Scripting', desc:'API and workflow for writing custom Instruction subclasses via CustomInstruction delegates.',                      keywords:'custom instruction create API workflow CustomInstruction' },
  { url:'sc-tasks.html',             title:'Tasks',                       category:'Scripting', desc:'ITaskReceiver interface and async Task system for scheduling per-turn work.',                                       keywords:'Task ITaskReceiver async turn schedule GetTask Status Running Completed' },

  // ── Scripting — Interactables ──────────────────────────
  { url:'sc-iinteractable.html',     title:'IInteractable',              category:'Scripting', desc:'Marks a world object as interactable. Called by Instruction_Interact when the player interacts.',                    keywords:'IInteractable interact Validate Interact automatic OnInteract' },
  { url:'sc-icarryobject.html',      title:'ICarryObject',               category:'Scripting', desc:'Marks an object as carryable by the player. Instruction_Carry picks it up; Instruction_Drop releases it.',        keywords:'ICarryObject carry Take Drop carryable object' },
  { url:'sc-ipushable.html',         title:'IPushable',                  category:'Scripting', desc:'Marks an object as pushable. Instruction_Push moves it one tile with collision validation.',                      keywords:'IPushable push Validate Push Stop pushable' },
  { url:'sc-iobstacle.html',         title:'IObstacle',                  category:'Scripting', desc:'Tags an object as a physical blocker. Used by movement and push validation to detect walls and doors.',              keywords:'IObstacle blocking obstacle Validate blocked passable' },
  { url:'sc-execution-context-element.html', title:'ExecutionContextElement', category:'Scripting', desc:'Abstract base class for all world objects in level execution. Cloned at play start for reversible gameplay.',    keywords:'ExecutionContextElement execute clone Initialize context parent IsRoot' },
  { url:'sc-builtin-interactables.html',title:'Built-in Interactables',  category:'Scripting', desc:'Reference for all built-in world objects: doors, crates, levers, pickups and more.',                             keywords:'builtin interactable door crate lever pickup tile built-in' },
  { url:'sc-traps.html',             title:'Traps',                       category:'Scripting', desc:'PressurePlate and AppearingSpikes — automatic turn-based tile traps with damage and events.',                      keywords:'trap PressurePlate AppearingSpikes spikes tile damage health stages appearing' },

  // ── Scripting — Inventory ──────────────────────────────
  { url:'sc-inventory.html',         title:'PlayerInventory',             category:'Scripting', desc:'Singleton inventory — add/remove items, query equipped gear and get stat totals.',                                  keywords:'PlayerInventory inventory singleton item equipment stat Add Remove GetStatValue' },
  { url:'sc-items.html',             title:'Item',                        category:'Scripting', desc:'Base ScriptableObject for collectible items — display name, icon, stackable flag, and ApplyEffects for stat modifications.',  keywords:'Item ScriptableObject collectible ApplyEffects effects stackable displayName image' },
  { url:'sc-equipment.html',         title:'Equipment',                   category:'Scripting', desc:'Extends Item with an equipment slot type and passive stat bonuses — Equipment.Type enum, StatValue pairs.',               keywords:'Equipment ScriptableObject slot type Weapon Shield Helmet Armor Boots twoHanded GetStatValue StatValue' },

  // ── Scripting — Level & Utility ───────────────────────
  { url:'sc-level-goals.html',        title:'LevelGoal',                   category:'Scripting', desc:'Abstract base for level challenge goals — subclass to define custom star objectives evaluated against LevelData.',      keywords:'LevelGoal goal level star Check displayText LevelData custom create InstructionCount LoopCount' },
  { url:'sc-level-manager.html',     title:'LevelManager',                category:'Scripting', desc:'Controls level lifecycle — Play, Pause, Observe, Stop and ResetLevel.',                                            keywords:'LevelManager level play pause observe stop reset transition lifecycle singleton' },
  { url:'sc-map-manager.html',       title:'MapManager',                  category:'Scripting', desc:'Tilemap utilities — world-to-cell conversion, cellSize constant and GetTile queries.',                             keywords:'MapManager map tilemap cell position cellSize GetTile world convert' },
  { url:'sc-notification.html',      title:'NotificationCenter',          category:'Scripting', desc:'Static notification bus — call Notify() to send UI feedback messages to the player.',                              keywords:'NotificationCenter notification message UI feedback static Notify MessageType' },

  // ── Scripting — Scriptable Objects ───────────────────
  { url:'sc-scriptable-objects.html', title:'IdentifiableSO',              category:'Scripting', desc:'Abstract base class for ScriptableObjects with a persistent GUID-based ID — used by Item, Equipment, and LevelInfo for save-safe asset references.',  keywords:'IdentifiableSO ScriptableObject ID GUID persistent save reference base class' },
  { url:'sc-stat.html',              title:'Stat',                         category:'Scripting', desc:'Named ScriptableObject key for a character attribute — links equipment bonuses and item effects to a shared identifier.',                          keywords:'Stat ScriptableObject displayName icon description damage defense attribute key' },
  { url:'sc-effect.html',            title:'Effect',                       category:'Scripting', desc:'Serializable stat modification embedded in Item assets — controls value, duration, and per-turn application for timed or instant stat changes.',       keywords:'Effect serializable stat modification targetStat value duration applyPerTurn regeneration damage-over-time HUD' },
  { url:'sc-items-references.html',  title:'ItemsReferences',              category:'Scripting', desc:'ScriptableObject that holds the master list of all Item assets — read by DatabaseManager at startup to build the runtime item database.',            keywords:'ItemsReferences ScriptableObject Items DatabaseManager master list Contains Add RemoveAll' },

  // ── Scripting — Audio ─────────────────────────────────
  { url:'sc-sound-manager.html',     title:'SoundManager',                category:'Scripting', desc:'Singleton for SFX playback and AudioMixer volume control via Set().',                                              keywords:'SoundManager audio SFX sound effect play mixer volume Set singleton' },
  { url:'sc-music-manager.html',     title:'MusicManager',                category:'Scripting', desc:'Singleton for background music playback with crossfade support.',                                                   keywords:'MusicManager music BGM crossfade play loop singleton' },
  { url:'sc-sound-slider.html',      title:'SoundSlider',                 category:'Scripting', desc:'UI helper that links a Unity Slider to a SoundManager AudioMixer parameter.',                                      keywords:'SoundSlider UI slider mixer volume settings audio OnValueChanged' },

  // ── Manual — UI ───────────────────────────────────────
  { url:'manual-ui.html',            title:'UI Setup',                    category:'Manual',    desc:'Configuring player and enemy HUD bars, inventory window, notifications, win screen and custom Window subclasses.', keywords:'UI HUD health stamina bar window inventory notification win screen custom Window setup' },

  // ── Scripting — Instructions (runtime) ───────────────
  { url:'sc-action.html',            title:'Action',                      category:'Scripting', desc:'MonoBehaviour bridge between an instruction C# type and its InstructionLayout prefab — lives on each draggable palette item.',     keywords:'Action instructionType layout CreateInstruction CreateLayout Load palette drag' },
  { url:'sc-instruction-sheet.html', title:'InstructionSheet',            category:'Scripting', desc:'Singleton UI manager for the instruction sheet — owns the layout list, drop handling, execution cursor, and undo/redo history.',  keywords:'InstructionSheet current singleton Insert Remove ClearSheet Undo Redo Load pointer cursor undo history' },
  { url:'sc-instruction-runner.html',title:'InstructionRunner',           category:'Scripting', desc:'Execution engine that cycles through instructions turn by turn, schedules parallel tasks, and fires success/failure events.',       keywords:'InstructionRunner Play Stop Observe Reset ExecutionStatus OnTurnStart OnTurnEnd OnSucceed OnFail TaskSchedule' },

  // ── Scripting — UI ────────────────────────────────────
  { url:'sc-window.html',            title:'Window',                      category:'Scripting', desc:'Abstract base class for all modal windows — toggles the GameObject on Open/Close and plays optional sound effects.',  keywords:'Window Open Close modal base class sound openSound closeSound subclass' },
  { url:'sc-hud.html',               title:'HUD',                         category:'Scripting', desc:'PlayerHealthBar, PlayerStaminaBar and HUD_ShowStatEffectNumber — live stat display components that auto-subscribe to LevelManager events.', keywords:'HUD health stamina bar toggle hearts pips damage floating numbers ShowNumber ShowBlockSign DefaultExecutionOrder' },
  { url:'sc-inventory-ui.html',      title:'Inventory UI',                category:'Scripting', desc:'InventoryWindow singleton, ItemSlotLayout, EquipmentSlotLayout and the floating equipment tooltip.',               keywords:'InventoryWindow inventory UI slot item equipment tooltip refresh current StatSlot Refresh ItemSlotLayout EquipmentSlotLayout' },
  { url:'sc-instruction-layout.html',    title:'InstructionLayout',           category:'Scripting', desc:'Base widget class for rendering instructions on the instruction sheet. Handles line numbers, loops, directions, and drag operations.',            keywords:'InstructionLayout base widget instruction sheet CreateInstance Load Remove IncreaseLoop DecreaseLoop SetDirection CycleDirection' },
  { url:'sc-instruction-modifier-layout.html', title:'InstructionModifierLayout', category:'Scripting', desc:'Widget for InstructionModifier subclasses. Extends InstructionLayout to add a child instruction drop zone.',  keywords:'InstructionModifierLayout modifier child instruction drop zone SetInstruction SetDirection' },
  { url:'sc-instruction-sequence-layout.html', title:'InstructionSequenceLayout', category:'Scripting', desc:'Widget for InstructionSequence subclasses (Combo, Ping Pong). Manages nested child layouts and implements IInstructionSequenceLayout.',  keywords:'InstructionSequenceLayout sequence nested children combo AddInstruction RemoveInstruction Insert' },
  { url:'sc-instruction-use-layout.html',     title:'InstructionUseLayout',     category:'Scripting', desc:'Widget for the Use instruction. Extends InstructionLayout with an item picker button for selecting consumable items.',   keywords:'InstructionUseLayout Use instruction item picker OpenInventory SetItem LoadItem' },
  { url:'sc-notification-layout-ui.html',    title:'NotificationLayout',       category:'Scripting', desc:'Generic toast notification that displays an icon and message for 7 seconds, then auto-dismisses.',                     keywords:'notification toast popup icon message dismiss CreateInstance Close timer unscaled' },
  { url:'sc-equipment-notification.html',    title:'EquipmentNotification',     category:'Scripting', desc:'Persistent notification panel that queues equipment announcements with stats and effects across scene loads.',          keywords:'EquipmentNotification equipment notification queue panel globe stats effects AddEquipment ActivateGlobe' },
  { url:'sc-drag-and-drop.html',             title:'DragAndDrop',              category:'Scripting', desc:'Implements drag-and-drop handlers to enable instruction reordering. Manages ghost copies and cursor following.',      keywords:'DragAndDrop drag drop instruction reordering ghost cursor currentDragging dragCaptured dragging leaveInstance' },
  { url:'sc-drop-action-event-caller.html',  title:'DropActionEventCaller',    category:'Scripting', desc:'Lightweight drop zone for accepting dragged instructions and invoking callbacks.',                                   keywords:'DropActionEventCaller drop zone lightweight instruction callback AddDropEvent OnDrop IDropHandler' },

  // ── Scripting — Components ────────────────────────────
  { url:'sc-character-instance-controller.html', title:'CharacterInstanceController', category:'Scripting', desc:'Abstract base class for all character entities. Provides animation, audio, health, directional sprite flipping, and blocking state. Subclass to add a new character type.', keywords:'CharacterInstanceController abstract base character animation audio health direction blocking damage defense SetDirection PlayAnimation Initialize OnInitialize ExecutionContextElement player enemy subclass' },
  { url:'sc-player-controller.html', title:'PlayerController', category:'Scripting', desc:'Root MonoBehaviour for the player prefab. Manages inventory-driven damage and defense stats, stamina, item usage visual effects, audio, and tile position validation.', keywords:'PlayerController player root MonoBehaviour stamina damage defense UseItem ValidatePosition OnExecute Initialize damageStat defenseStat useItemFX useItemParticles CharacterInstanceController ActiveEffectsController' },
  { url:'sc-enemy-controller.html',  title:'EnemyController',  category:'Scripting', desc:'Root MonoBehaviour for enemy prefabs. Controls patrol routing, player detection, attack-sequence cycling, hover highlighting of attack range tiles, and IObstacle blocking.', keywords:'EnemyController enemy root MonoBehaviour patrol detection attack sequence IObstacle ITaskReceiver GetTask moveSequence attackSequence EnemyActionInstance OnActionChange OnExecute OnMouseHover range directions blocking CharacterInstanceController' },
  { url:'sc-player-stamina.html',     title:'PlayerStamina',               category:'Scripting', desc:'Tracks the player stamina resource with events for HUD display and methods to spend or restore points from instructions.',          keywords:'PlayerStamina stamina Substract Add OnDepleted OnReplenished OnInitialize OnValueUpdated stat player resource' },
  { url:'sc-health.html',             title:'Health',                      category:'Scripting', desc:'Abstract health base class with damage, block, heal, and kill methods. PlayerHealth and EnemyHealth extend it with character-specific behaviour.', keywords:'Health PlayerHealth EnemyHealth ApplyDamage Heal Kill OnDie OnDamageApplied OnDamageBlocked maxHealth currentHealth blocking defense abstract' },
  { url:'sc-active-effects-controller.html', title:'ActiveEffectsController', category:'Scripting', desc:'Tracks all active timed stat effects on the player, decrements their remaining turns each turn, and reverts them on expiry.', keywords:'ActiveEffectsController timed effect duration Track Clear revert stat expires turns active' },
  { url:'sc-enemy-hud.html',          title:'Enemy HUD',                   category:'Scripting', desc:'Four components for the in-world enemy display: health counter, animated action indicator, full action-sequence panel, and per-action layout widget.', keywords:'EnemyHealthBar EnemyInstructionIndicator EnemyActionSequencePanel EnemyAction_Layout enemy HUD health indicator sequence panel icon loops' },
  { url:'sc-item-dropper.html',       title:'ItemDropper',                 category:'Scripting', desc:'Spawns a pickup at the entity tile position on death. ItemUsedFX briefly flashes an item sprite at the use position.',           keywords:'ItemDropper Drop pickup loot spawn death OnDie InteractableObject_Pickup ItemUsedFX sprite flash CreatInstance' },
  { url:'sc-game-data-manager.html',  title:'GameDataManager',             category:'Scripting', desc:'Singleton that persists level progress, audio settings, and discovered equipment. All members are static — no instance reference needed.', keywords:'GameDataManager SaveLevel GetLevelData SaveSoundSetting GetSoundSetting GetAllSoundSettings SaveNow AddDiscoveredEquipment DiscoveredEquipment singleton save persist' },
  { url:'sc-database-manager.html',   title:'DatabaseManager',             category:'Scripting', desc:'Singleton that indexes every item asset from an ItemsReferences asset into fast type-specific lookup tables at startup.',           keywords:'DatabaseManager current singleton ItemsReferences items database lookup type index startup' },
  { url:'sc-world-map.html',          title:'World Map',                   category:'Scripting', desc:'WorldMapManager orchestrates map initialization. LevelMarker represents selectable level nodes with star ratings and unlock chaining.', keywords:'WorldMapManager LevelMarker Initialize CheckCompleted childs starsSprites active level OpenLevelInfoScreen world map unlock progression' },
  { url:'sc-level-screens.html',      title:'Level Screens',               category:'Scripting', desc:'LevelInfoScreen, LevelGoalLayout, WinScreenController, GameOptionsMenu, and ItemsListWindow — UI screens for before and after gameplay.', keywords:'LevelInfoScreen LevelGoalLayout WinScreenController GameOptionsMenu ItemsListWindow Open Close PlayLevel ResetLevel GoToWorldMap screens UI' },
  { url:'sc-equipment-browser.html',  title:'Equipment Browser',           category:'Scripting', desc:'DiscoveredEquipmentList paginated panel, DiscoveredEquipment_Layout entry widget, and StatElement and EffectElement tooltip layouts.', keywords:'DiscoveredEquipmentList DiscoveredEquipment_Layout StatElement_Layout EffectElement_Layout ShowType Next Previous CreateInstance equipment browser paginated' },
  { url:'sc-projectile.html',         title:'Projectile',                  category:'Scripting', desc:'Self-propelled component that travels in a straight line and applies damage on impact. Fire with Shoot() from an instruction or via ShootSuscriber on enemies.', keywords:'Projectile Shoot speed damage shootSound hitSound Initialize direction ranged ShootSuscriber enemy' },
  { url:'sc-visual-fx.html',          title:'Visual FX',                   category:'Scripting', desc:'SpriteExpandAnimation and SinExpandAnimation for breathing effects, HoveringMouse for hover scale, and CloudsController for procedural drifting clouds.', keywords:'SpriteExpandAnimation SinExpandAnimation HoveringMouse CloudsController breathing pulse hover scale clouds speed amplitude horizontal vertical' },
  { url:'sc-utility-components.html', title:'Utilities',                   category:'Scripting', desc:'DisableOnRunning and DisableButtonOnRunning lock UI during play. PixelSnaper snaps to pixel or grid. DepthSortingOrder drives Y-based painter depth.', keywords:'DisableOnRunning DisableButtonOnRunning PixelSnaper DepthSortingOrder pixel snap grid Y sorting depth running UI canvas button' },

  // ── Manual — Setup Guides ─────────────────────────────
  { url:'manual-player-setup.html',      title:'Player Setup',             category:'Manual',    desc:'Configure PlayerHealth, PlayerStamina, and ActiveEffectsController on the player GameObject and wire events to the HUD.', keywords:'player setup PlayerHealth PlayerStamina ActiveEffectsController HUD health stamina wiring events' },
  { url:'manual-enemy-setup.html',       title:'Enemy Setup',              category:'Manual',    desc:'Configure EnemyHealth, optional ItemDropper loot drop, and the four enemy HUD components on an enemy prefab.',          keywords:'enemy setup EnemyHealth ItemDropper HUD EnemyHealthBar EnemyInstructionIndicator EnemyActionSequencePanel prefab' },
  { url:'manual-data-systems.html',      title:'Data Systems',             category:'Manual',    desc:'Set up DatabaseManager and GameDataManager as persistent singletons. Save and read level progress and discovered equipment.',keywords:'data systems DatabaseManager GameDataManager save load level progress discovered equipment persistent singleton setup' },
  { url:'manual-world-map-setup.html',   title:'World Map',                category:'Manual',    desc:'Build the world map scene with WorldMapManager and LevelMarker nodes chained for unlock progression and star ratings.',  keywords:'world map WorldMapManager LevelMarker LevelInfoScreen setup unlock chain stars progression scene' },
  { url:'manual-ui-screens.html',        title:'UI Screens',               category:'Manual',    desc:'Configure the win screen, options menu, and item list window. All extend Window and follow the same open/close pattern.',keywords:'UI screens WinScreenController GameOptionsMenu ItemsListWindow Window Open Close setup level' },
  { url:'manual-projectile-setup.html',  title:'Projectile',               category:'Manual',    desc:'Create a projectile prefab and fire it from a ranged instruction or attach ShootSuscriber to an enemy.',               keywords:'projectile setup Projectile Shoot ShootSuscriber ranged prefab speed damage instruction enemy' },
  { url:'manual-visual-fx-setup.html',   title:'Visual FX & Utilities',    category:'Manual',    desc:'Drop-in components for breathing animations, hover effects, clouds, UI state locking during play, pixel snapping, and depth sorting.', keywords:'visual FX utilities SpriteExpandAnimation SinExpandAnimation HoveringMouse CloudsController DisableOnRunning PixelSnaper DepthSortingOrder breathing hover clouds pixel snap depth' },
];
